### ISSUE TITLE
Is this function better than yours? (IsPlayerSpawned)

### ISSUE THREAD

**Issue by AmirSavand** [NiketGandhir/functions.inc#3]
So I found this in some post, I'm wondering if this function is better or yours is better:

```
stock bool:IsPlayerSpawned(playerid)
{
    new playerState = GetPlayerState(playerid);
    return ((playerState >= 1 && playerState <= 6) || playerState == 8);
}
```

**Comment by NiketGandhir** [comment]
The function you mentioned, and the function in the include are both same. Both depends on PlayerState to  check if a player is spawned or not. But I'll still prefer the one in the function because it uses names instead of ID so its more direct and understandable for anyone who uses that code.
